"""fix case unique index

Revision ID: 17efef2e5231
Revises: 
Create Date: 2026-08-28 18:02:55.442706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17efef2e5231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_codigo_unico'), table_name='casos')
    op.create_index(op.f('ix_casos_codigo_unico'), 'casos', ['codigo_unico'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_codigo_unico'), table_name='casos')
    op.create_index(op.f('ix_casos_codigo_unico'), 'casos', ['codigo_unico'], unique=True)
    # ### end Alembic commands ###
